### ISSUE TITLE
Use RawGit production links for workshop images

### ISSUE THREAD

**Issue by jaredkhan** [hackersatcambridge/hac-website#198]
For background, see here: http://rawgit.com for the difference between RawGit's dev and production URLs

Currently we're using RawGit development URLs for serving images in workshops (search rawgit.com in the codebase to see where). This needs to be changed before people can visit the workshops pages.

This will likely involve adding to GitUtil to find the latest commit hash of each of the repos and then using this in the URL.

**Comment by Pinpickle** [comment]
@jaredkhan Going to hold off on this until #199, because currently we don't have a repo pulled for each workshop and this is an important detail for the production URLs (which rely on the commit hash).

Yes, we can put dummy data in but the overhead of splitting it in two is not worth it for the difficulty of implementing this (it's rather simple to do the whole thing in one sweep). Besides, in this case, plugging the data in is the hardest part (using it is simple string interpolation).

**Comment by Pinpickle** [comment]
I'm talking nonsense, was reading `WorkshopsManager` and not `NewWorkshopsManager`.

I'll re-assess the situation.
